### ISSUE TITLE
example code not working

### ISSUE THREAD

**Issue by Blackhawk2165** [traviswimer/dir-to-json#1]
Hello,

I'm trying to convert a directory of documents i.e. word, powerpoint, excel, and others to json format. I downloaded your converter and put the example code you have up in a file called handler.java. When I ran the code I got these two errors:
1. line 1: syntax error near unexpected token '('
2. line 1: 'var dirToJson = require('dir-to-json');'

maybe I'm going about this the wrong way but I'm not sure how else to do it. Let me know what you think.
Thanks,
Austin Harmon

**Comment by traviswimer** [comment]
Well... I guess that's what happens when you run Javascript through a Java compiler. :-)
