### ISSUE TITLE
Multiples strings with path, one single JSON output.

### ISSUE THREAD

**Issue by maycowmeira** [traviswimer/dir-to-json#2]
Hi,

Is it possible to use your project over a list of strings to build a single json file?

Thanks.

**Comment by traviswimer** [comment]
I'm not sure I understand what you're asking. Are you asking if an array of directories can be passed in instead of a single directory as a  string?

**Comment by maycowmeira** [comment]
Exactly.

**Comment by traviswimer** [comment]
The path parameter must be a string, so no it will not work with an array.

I don't really see why accepting an array would be very helpful though. I think it is more flexible to just use whatever method of iteration you want to call `dir-to-json` with each path, than to abstract a specific method of iteration inside the library.

**Comment by traviswimer** [comment]
closing
